### ISSUE TITLE
Logger issues

### ISSUE THREAD

**Issue by miks** [RubyDevInc/paho.mqtt.ruby#10]
I believe there is error on 
https://github.com/RubyDevInc/paho.mqtt.ruby/blob/master/lib/paho-mqtt.rb#L109

When I try to set logger, it's raising error about nil object:
```
PahoMqtt.logger = Rails.root.join("log", "paho.log").to_s
NoMethodError: undefined method `logger=' for nil:NilClass
```

Also, it's strange that sample at https://github.com/RubyDevInc/paho.mqtt.ruby/blob/master/samples/test_client.rb#L8 still contains "logger" option that was removed with https://github.com/RubyDevInc/paho.mqtt.ruby/commit/6ad9c3f08b56bedacd93167bf0bfd6d2fe404ed9#diff-a4d6bfdac36637744087393a190c31a5

What is recommended approach to enable logger?

**Comment by p-goudet** [comment]
Thank you for you comment. 
Your are right, and the sample files seems to be out of date. 
The logger features have been moved for the Client Class to the PahoMqtt modules, but a variable seems to be misspelled on the accessor method.
A new update would be issue soon to fix the sample files and the logger feature.
The approach to set up a log file would be : 
```
PahoMqtt.logger = "...."
```

**Comment by miks** [comment]
Do I need to make PR for this?

**Comment by miks** [comment]
Also, we got error like this:
`
undefined method 'logger?' for #<PahoMqtt::Subscriber:0x00000803d249b0> in [GEM_ROOT]/gems/paho-mqtt-1.0.2/lib/paho_mqtt/subscriber.rb on line 69.
`

While https://github.com/RubyDevInc/paho.mqtt.ruby/blob/master/lib/paho_mqtt/subscriber.rb#L69
there is call to `PahoMqtt.logger?` not `PahoMqtt::Subscriber` instance.
Any ideas?

**Comment by p-goudet** [comment]
Thank you again for pointing that out.
Yes you the logger management belongs to the module and not anymore in the sub-classes.
This feature has been fixed in the latest sources, and the gem package should be updated soon.
In the meantime, you can download the  source and install the gem locally.
```bash
git clone https://github.com/RubyDevInc/paho.mqtt.ruby
cd paho.mqtt.ruby
gem build paho-mqtt.gemspec
gem install paho-mqtt-1.0.3.gem
gem list ---local paho-mqtt
```

**Comment by miks** [comment]
Are there ETA for gem release?

**Comment by p-goudet** [comment]
I am sorry, could you tell me what does ETA stand for?

**Comment by miks** [comment]
`Estimated Time of Arrival` aka when you plan to release a gem.

**Comment by p-goudet** [comment]
The new gem version have released!
Thank you for waiting. Could you confirm if the logger issue has been fixed?

**Comment by miks** [comment]
Sure.
