### ISSUE TITLE
Subscriber seems to be nil

### ISSUE THREAD

**Issue by Wachiwi** [RubyDevInc/paho.mqtt.ruby#41]
Hey there, perhaps I did a stupid mistake, but I cannot completely trace back and solve the error I am receiving. First of all the error message itself:

```
...paho-mqtt-1.0.11/lib/paho_mqtt/client.rb:236:in `subscribe': undefined method `send_subscribe' for nil:NilClass (NoMethodError)
```

What I want is to subscribe to all topics on `connack`. So I set *all* necessary options and try to connect via the following code: 

```ruby
...
@mqtt_client = PahoMqtt::Client.new({
          host: @mqtt_endpoint, # => resolves to 'localhost'
          port: @mqtt_port, # => resolves to '1883'
          ssl: false,
          client_id: @c_id, # =>random hash
          clean_session: false
})

...
@mqtt_client.on_connack = self.method(:on_connect).to_proc
....
@mqtt_client.connect
```

The connect itself is kinda simple and only subscribes to all subtopics inside a specific topic:

```ruby
def on_connect(data)
  puts "Connected!"
  @mqtt_client.subscribe(["#{@c_id}/#", 1])
end
```

When executing this I get the error as described above. So I looked into the [client.rb:236](https://github.com/RubyDevInc/paho.mqtt.ruby/blob/master/lib/paho_mqtt/client.rb#L233) to figure out what mistake I made. 

```ruby 
def subscribe(*topics)
...
   unless @subscriber.send_subscribe(topics, id) == PahoMqtt::MQTT_ERR_SUCCESS
        reconnect if check_persistence
   end
...
end
```

This code led me to the subscriber creation since it was missing, which should get created by [`build_pubsub()`](https://github.com/RubyDevInc/paho.mqtt.ruby/blob/master/lib/paho_mqtt/client.rb#L371). This relies IMO on the existence of an `@sender` which I couldn't find to get set. 

Since I didn't know anything specific about why or what happened there I wanted to ask for help to solve the error above.

**Comment by p-goudet** [comment]
The connack callback is called before `build_pubsub()`, so the subscriber is not initialize yet at this moment. I will try to change this.

**Comment by Wachiwi** [comment]
@p-goudet thx for that, If you think I can help pls let me know.

**Comment by Wachiwi** [comment]
@p-goudet  After giving it a first try it seems to be working for me. Thank you very much.
