### ISSUE TITLE
Support EC private keys

### ISSUE THREAD

**Issue by consulthys** [RubyDevInc/paho.mqtt.ruby#42]
We're using the [`logstash-input-mqtt`](https://github.com/jurek7/logstash-input-mqtt) plugin which leverages the `paho.mqtt.ruby` library. Recently, `logstash-input-mqtt` [added support for SSL certificates](https://github.com/jurek7/logstash-input-mqtt/issues/7) in their configuration.

One issue we've encountered was that the `paho.mqtt.ruby` library only supports RSA private keys and we're using an EC one. We can clearly see that the [`SSLHelper` module makes the assumption](https://github.com/RubyDevInc/paho.mqtt.ruby/blob/047769f3598242da862319c2de23cf1d5d6472ae/lib/paho_mqtt/ssl_helper.rb#L34-L36) that the private key is an RSA one and hence we get an error like the following one:
```
  Error: Neither PUB key nor PRIV key: (invalid key type org.jruby.ext.openssl.impl.ECPrivateKeyWithName)
  Exception: OpenSSL::PKey::RSAError
  Stack: org/jruby/ext/openssl/PKeyRSA.java:318:in `initialize'
```

The problem could be easily solved by adding a new method to set up an EC key:
```
    def set_ec_key(key_path, ssl_context)
       ssl_context.key = OpenSSL::PKey::EC.new(File.read(key_path))
    end
```
We also probably need another `config_ssl_context` method to call that new method. You might be better inspired on how to support this, but the main idea is to be able to provide both EC and RSA private keys, since the latter is quickly gaining ground over RSA in terms of performance and security.

If this can be done, it'll be easy to modify the Logstash plugin in order to support this.
Thanks for considering this.

**Comment by rgaufman** [comment]
@consulthys off topic but do you have any more details/links about the advantages of EC and where/why it is gaining ground?

**Comment by p-goudet** [comment]
@consulthys Thank you very for this information. Upgrade the safety of data is always a good idea. I will check this encryption approach. 
Thank you for providing some hints to supports EC encryption to the client.

**Comment by consulthys** [comment]
Thank you @p-goudet for considering this.

@rgaufman sure thing, Google is our friend
 * [Pro/cons of both on Quora](https://www.quora.com/Which-one-is-better-elliptic-curve-cryptography-or-RSA-algorithm-and-why)
 * [ECC vs RSA: battle of the crypto ninjas](https://fr.slideshare.net/JamesMcGivern/ecc-vs-rsa-battle-of-the-cryptoninjas) (slides 93-95 + 114/115)

To sum up, both RSA and ECC are still secure and ECC is not gaining ground because of better security but faster performance (256-bit ECC ~ 3072-bit RSA). We are using ECC as we need to display the signature and an ECC signature is shorter than an RSA one.

**Comment by consulthys** [comment]
@p-goudet would you welcome a PR?

**Comment by p-goudet** [comment]
@consulthys 
Yes, I would try to submit a PR soon.
 I am not a security expert so I want to learn a bit more about ciphers suites and how the client could support ciphers suites.

**Comment by p-goudet** [comment]
@consulthys  The version 1.0.12 should support the EC keys (and RSA). The method signature is unchanged.

**Comment by consulthys** [comment]
@p-goudet Fantastic and thanks a lot for your prompt reactivity!! I can now request changes in the `logstash-input-mqtt` project.
Cheers!!
