### ISSUE TITLE
include a copy of MIT license

### ISSUE THREAD

**Issue by shadowbq** [RubyDevInc/paho.mqtt.ruby#46]
There is only a single reference to the license, within the gemspec. Can you please include a copy of the MIT license.

**Comment by p-goudet** [comment]
Thank you for noticing this mistake in the gemspec. The project have been re-licensed and is now under the EPL (Eclipse Public License). I would fix the gemspec

**Comment by p-goudet** [comment]
I change the gemspec and add a copy of the Eclipse Public License.
